version: '3'
services:
#ADD TO SOLECTRUS DOCKER-COMPOSE FILE FROM HERE ON
  sungrow-inverter-importer:
    container_name: sungrow-inverter-importer
    build:
      context: .
      dockerfile: Dockerfile
    extra_hosts:
    - "host.docker.internal:host-gateway"
    environment:
      - INFLUX_HOST
      - INFLUX_ORG
      - INFLUX_BUCKET
      - INFLUX_MEASUREMENT_PV
      - INFLUX_TOKEN=${INFLUX_TOKEN_READ}
      - SUNGROW_IP_ADDR
    restart: always

